import type { Metadata } from "next";
import Image from "next/image";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-white dark:bg-gray-900" style={{
        backgroundImage: 'url(/topo.svg)',
        backgroundSize: 'cover',
        backgroundRepeat: 'repeat',
      }}>{children}</body>
    </html>
  );
}
